version: "3.4"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./deployment/laravel/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - store-backend
        depends_on:
            - pgsql

    #Nginx Service
    webserver:
        image: nginx:1.17-alpine
        ports:
            - "9000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - store-backend

    #Batch
    php-batch:
        build:
            context: .
            dockerfile: deployment/batch/Dockerfile
        volumes:
            - ./:/var/www
        networks:
            - store-backend
        depends_on:
            - pgsql

    # Database
    pgsql:
        image: "postgres:14"
        ports:
            - "6543:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - pgsql:/var/lib/postgresql/data
        networks:
            - store-backend
networks:
    store-backend:
        driver: bridge
volumes:
    pgsql:
        driver: local
