version: '2.1'
services:
  laravel:
    build:
      context: ../
      dockerfile: deployment/laravel/Dockerfile
    image: nodeye
    networks:
      - backend

  nginx:
    build:
      context: ../
      dockerfile: deployment/nginx/Dockerfile
    image: nodeye-nginx
    ports:
      - ${DOCKER_NGINX_EXTERNAL_PORT-8000}:80
    restart: always
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - laravel
    links:
      - laravel
    networks:
      - backend

networks:
  backend:
    driver: bridge
