<?php

namespace App\Enums;

enum ExceptionErrorCode: int
{
    // Login: 11xx
    case LOGIN_EMAIL_REQUIRED = 1101;
    case LOGIN_EMAIL_DOES_NOT_EXIST = 1102;
    case LOGIN_PASSWORD_REQUIRED = 1103;
    case LOGIN_PASSWORD_INCORRECT = 1104;

    // register: 12xx
    case REGISTER_FULLNAME_REQUIRED = 1201;
    case REGISTER_DISPLAYNAME_REQUIRED = 1202;
    case REGISTER_EMAIL_REQUIRED = 1203;
    case REGISTER_PASSWORD_REQUIRED = 1204;
    case REGISTER_EMAIL_EXISTED = 1205;
    case REGISTER_PASSWORD_NOT_CONFIRMED = 1206;
    case REGISTER_PHONE_NUMBER_REQUIRED = 1207;
    // case REGISTER_PROFILE_IMAGE_FILE_EXCEEDS_THE_ALLOWABLE_LIMIT = 1207;
    // case REGISTER_PROFILE_IMAGE_FILE_MUST_BE_IMAGE = 1208;

    // resend: 13xx
    case RESEND_EMAIL_VERIFY_EMAIL_REQUIRED = 1301;
    case RESEND_EMAIL_VERIFY_EMAIL_DOES_NOT_EXIST = 1302;
    case RESEND_EMAIL_VERIFY_EMAIL_VERIFIED = 1303;
    // refresh token: 14xx
    case REFRESH_TOKEN_REQUIRED = 1401;

    // fail response: 403x
    case EMAIL_NOT_VERIFIED = 4031;

    // not found: 404x;
    case API_ENDPOINT_NOT_FOUND = 4040;

    // authentication: 401x
    case AUTHENTICATION_FAILED = 4010;
    case AUTHENTICATION_ACCESS_TOKEN_INVALID = 4011;
    case AUTHENTICATION_ACCESS_TOKEN_EXPIRED = 4012;
    case AUTHENTICATION_REFRESH_TOKEN_INVALID = 4013;
    case AUTHENTICATION_ACCESS_TOKEN_INVALID_SCOPE = 4014;
    
    // Server: 50xx
    case INTERNAL_SERVER_ERROR = 5001;
}

?>